export const FETCH_TOP_RATED_MOVIES = "FETCH_TOP_RATED_MOVIES";
export const FETCH_UPCOMING_MOVIES = "FETCH_UPCOMING_MOVIES";
export const SEARCH_MOVIES_BY_TITLE = "SEARCH_MOVIES_BY_TITLE";
export const SEARCH_MOVIES_BY_GENRE = "SEARCH_MOVIES_BY_GENRE";
export const FETCH_MOVIE_DETAILS = "FETCH_MOVIE_DETAILS";
export const FETCH_MOVIES_BY_GENRE = "FETCH_MOVIES_BY_GENRE";
